In [1]:
#importing_libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#importing_datasets

In [4]:
data_train = pd.read_csv("//Users/nilotpal//Downloads//mnist_train_small.csv")
data_test = pd.read_csv("//Users/nilotpal//Downloads//mnist_test.csv")

In [5]:
data_train

6  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0      5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1      7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2      9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3      5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4      2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...   .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
19994  0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19995  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19996  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19997  9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19998  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   

       0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0  

[19999 rows x 785 columns]

In [6]:
#train_dataset_arrangement

In [7]:
#x_feature_seperation
x1 = data_train.drop(['6'], axis = 1).values
train_x0 = np.ones((np.shape(x1)[0],1))
train_x = np.hstack((train_x0,x1))
train_x = train_x/255

In [8]:
print(train_x)
train_x.shape

[[0.00392157 0.         0.         ... 0.         0.         0.        ]
 [0.00392157 0.         0.         ... 0.         0.         0.        ]
 [0.00392157 0.         0.         ... 0.         0.         0.        ]
 ...
 [0.00392157 0.         0.         ... 0.         0.         0.        ]
 [0.00392157 0.         0.         ... 0.         0.         0.        ]
 [0.00392157 0.         0.         ... 0.         0.         0.        ]]


(19999, 785)

In [9]:
#seperating_y_value
y1 = data_train['6']
train_y = y1.to_numpy()
train_y = np.vstack(train_y)

In [10]:
print(train_y)
train_y.shape

[[5]
 [7]
 [9]
 ...
 [2]
 [9]
 [5]]


(19999, 1)

In [11]:
import numpy as np
theta = np.zeros((785,1))
def GradientDescent(train_x, train_y, theta, alpha, iterations):
        m = train_y.size #number_of_training_examples
        cost = [] #emptylist_costfunction
        for i in range(0,iterations):
            pred_y = np.dot(train_x, theta) #predicted_value_matrix_multiplication
            cost_func = (1/(2*m))*np.sum((pred_y-train_y)**2)
            d_theta = (1/m)*np.dot(train_x.T, pred_y-train_y) #differentiate_cost_function
            
            theta = theta-alpha*d_theta #updation
            cost.append(cost_func)
        return cost,theta

In [96]:
cost, theta = GradientDescent(train_x, train_y, theta, 0.018, 2500)

In [97]:
print(theta)
theta.shape

[[ 2.74772959e-01]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-1.41884010e-03]
 [-3.06469463e-02]
 [-3.06469463e-02]
 [-1.27695609e-03]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 6.69840815e-02]
 [ 1.12670827e-01]
 [ 1.15020855e-01]
 [ 1.00291320e-01]
 [ 5.91381567e-02]
 [-3.74269237e-02]
 [ 8.08786526e-02]
 [ 4.25394322e-02]
 [ 1.10093545e-01]
 [ 1.64660531e-01]
 [ 1.31156874e-01]
 [ 8.14513474e-02]
 [ 1.27891670e-01]
 [ 5.93745997e-02]
 [ 5.06841422e-02]
 [ 4.10720970e-03]
 [ 0.00000000e+00]
 [ 0.0000000

(785, 1)

In [98]:
#arranging_test_dataset

In [99]:
data_test

7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0     2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2     0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3     4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4     1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...  .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
9994  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9995  3  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9996  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9997  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
9998  6  0    0    0    0    0    0    0    0    0  ...      0      0      0   

      0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0         0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...  
9994      0      0      0      0      0      0      0  
9995      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0  

[9999 rows x 785 columns]

In [100]:
#test_dataset_arrangement

In [101]:
#x_feature_seperation
xt1 = data_test.drop(['7'], axis = 1).values
test_x0 = np.ones((np.shape(xt1)[0],1))
test_x = np.hstack((test_x0,xt1))
test_x = test_x/255

In [102]:
print(test_x)
test_x.shape

[[0.00392157 0.         0.         ... 0.         0.         0.        ]
 [0.00392157 0.         0.         ... 0.         0.         0.        ]
 [0.00392157 0.         0.         ... 0.         0.         0.        ]
 ...
 [0.00392157 0.         0.         ... 0.         0.         0.        ]
 [0.00392157 0.         0.         ... 0.         0.         0.        ]
 [0.00392157 0.         0.         ... 0.         0.         0.        ]]


(9999, 785)

In [103]:
#seperating_y_value
yt1 = data_test['7']
test_y = yt1.to_numpy()
test_y = np.vstack(test_y)

In [104]:
print(test_y)
test_y.shape

[[2]
 [1]
 [0]
 ...
 [4]
 [5]
 [6]]


(9999, 1)

In [105]:
#making_hypothesis

In [106]:
hypothesis = np.dot(test_x, theta)
print(hypothesis)
hypothesis.shape

[[1.94604119]
 [0.84459535]
 [1.35906825]
 ...
 [8.64914069]
 [5.97828186]
 [6.91619959]]


(9999, 1)

In [107]:
#equating_predicted_value_with_test

In [108]:
hypothesis = np.around(hypothesis)
accurate = 0

def accuracy(hypothesis, accurate):
    for i in range(9999):
        if hypothesis[i] == test_y[i]:
            accurate += 1
    accuracy = (accurate/test_y.size)*100
    return accuracy

In [109]:
print(accuracy(hypothesis, accurate))

23.982398239823983
