In [ ]:
#importing_libraries

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [15]:
#importing_datasets

In [16]:
data_train = pd.read_csv("//Users/nilotpal//Downloads//mnist_train_small.csv")
data_test = pd.read_csv("//Users/nilotpal//Downloads//mnist_test.csv")

In [17]:
data_train

6  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0      5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1      7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2      9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3      5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4      2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
...   .. ..  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...    ...   
19994  0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19995  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19996  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19997  9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
19998  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   

       0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0          0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...  
19994      0      0      0      0      0      0      0  
19995      0      0      0      0      0      0      0  
19996      0      0      0      0      0      0      0  
19997      0      0      0      0      0      0      0  
19998      0      0      0      0      0      0      0  

[19999 rows x 785 columns]

In [18]:
#dataset_arrangement

In [19]:
#x_feature_seperation
x1 = data_train.drop(['6'], axis = 1).values
train_x0 = np.ones((np.shape(x1)[0],1))
train_x = np.hstack((train_x0,x1))

In [20]:
print(train_x)
train_x.shape

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


(19999, 785)

In [21]:
#seperating_y_value
y1 = data_train['6']
train_y = y1.to_numpy()
train_y = np.vstack(train_y)

In [22]:
print(train_y)
train_y.shape

[[5]
 [7]
 [9]
 ...
 [2]
 [9]
 [5]]


(19999, 1)

In [4]:
class LinearRegression:
    def GradientDescent(train_x, train_y, alpha, iterations):
        m = train_y.size #number_of_training_examples
        theta = np.zeros((785,1))
        cost = [] #emptylist_costfunction
        
        for i in range(0,iterations):
            pred_y = np.dot(train_x, theta) #predicted_value_matrix_multiplication
            cost_func = (1/(2*m))*np.sum((pred_y-train_y)**2)
            d_theta = (1/m)*np.dot(train_x.T, pred_y-train_y) #differentiate_cost_function
            
            theta = theta-alpha*d_theta #updation
            cost.append(cost_func)
            return cost, theta
        cost, theta = GradientDescent(train_x, train_y, 0.01, 1500)